name: Test Action
on:
  workflow_dispatch:  
  
jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: hassanmehedi1/My-Github-Actions@v1.0.0
        with:
          person: 'CatWoman'